import Head from 'next/head'
import Header from '@/components/Header'
import Landing from '@/components/Landing'
import About from '@/components/About'
import Experience from '@/components/Experience'
import Projects from '@/components/Projects'
import Footer from '@/components/Footer'


export default function Home() {
  return (
    // <div className="bg-[#491f0fc1] text-white h-screen snap-y snap-mandatory  z-0">
    <div className="bg-[#653e2ee7] md:bg-[#542613dc] text-white  snap-y snap-mandatory  z-0">
      <Head>
        <title>Dimeji&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel='preload' href='/bg9.webp' as='image'/>
        <link rel='preload' href='/net2.svg' as='image'/>
      </Head>


      <Header/>

      <section id='landing' className='overflow-hidden snap-center h-[calc(100vh-70px)] flex flex-1' >
        <Landing />
      </section>

      <section className='snap-center z-2' id='about'
      >
        <About />
      </section>
      
      <section id='experience' className='snap-center z-2'
      >
        <Experience />
      </section>

      <section id='projects' 
      className='snap-center z-2'
      >
        <Projects/>
      </section>

      <section id='footer' 
      // className='bg-[#1e1d1d] overflow-hidden snap-center h-[100px] w-full flex flex-1' 
      className='bg-[#292929cd] overflow-hidden snap-center  w-full flex flex-1' 
      >
        <Footer/>
      </section>

    </div>
  )
}
